// v6.3.1607
(function(m,f,K,A,L,t,r,v,da,ea,fa,y,Q,B,R,w,ga,ha){function S(a,b,c){if(!a)for(a in q)return q[a];if(q[b||a])return q[b||a];var d=new ia(a);c&&d.fa();return q[b||a]=d}function qa(a,b){return function(){a.call(b)}}function C(a){return"object"==typeof a}function ra(){for(var a=32,b="";a--;)b+=(0|16*L.random()).toString(16);return b}function x(a,b,c,d){var e;(e=a.addEventListener)?e.call(a,b,c,0):a.attachEvent(d||"on"+b,c)}function s(a,b,c){return function(){a(b,c)}}function z(a,b){for(var c in a)a.hasOwnProperty(c)&&
a[c]!==p&&b(a[c],c)}function M(a,b){var c=[],d;z(a,function(a,g){d=(typeof a).charAt(0);c.push(da(g)+"="+da(b?d+("o"==d&&a?M(a,b):a):a))});return c.join("&")}function D(a,b){if(!a)throw Error(b);}function sa(a){var b={};z(a,function(a,d){b[d]=a});return b}function E(a,b,c,d){if(a&&a.call)a();else if(/^GSN-.*-.$/.test(a))b!==""+b&&(c=b,b=0),S(a,b,c||c===p);else if(/^_/.test(a))N[a]&&N[a](b,c),delete N[a];else{var e=function(a,b,c){g?q[g].s(a,b,c):z(q,function(d){d.s(a,b,c)})};a=a[y](".");var g;1<a[B]&&
(g=a.shift());a=a[0];var k={usecookies:1,anonymizeip:2,visitorname:3,username:3,statuscode:5,cookiedomain:6,trackparams:7,trackhash:8,tracklocal:9,referrer:10,visitorid:13,visitor:4,clientid:11,auth:14,props:4,properties:4};if(/transaction$/i.test(a))return ta(g,b,c,d);if("get"==a)return c=k[(b+"")[R]()]||b,g?d=q[g].g(c):z(q,function(a){d=a.g(c)}),d;"set"==a?(a=(b+"")[y]("."),b=a.shift(),e(k[b[R]()]||b,c,a.join("."))):"track"==a?F(U,g,b,c,d):"event"==a?F(V,g,b,c,d):"cancel"==a?F(function(){this.F()},
g):"noCookies"==a?e(1,0):"anonymizeIP"==a?e(2,1):"tag"==a?e(3,b):"load"==a?b&&b():"auth"==a?e(14,b):"identify"==a?F(ua,g,b,c,d):"alias"==a?e(13,b):"unidentify"==a?e(13):"props"!=a&&"properties"!=a||e(4,b)}}function ja(a,b,c){var d=a.f=a.f||{},e={};D(b||C(c),"Not an object");b?d[b]=e[b]=c:e=d=a.f=c;!a.aa&&a.D&&(a.aa=r(function(){ka(a)},100))}function W(a,b){function c(a){return"expires="+(new t(a)).toGMTString()+";"}var d="path=/;",e=a.g(6);e&&(d+="domain="+e+";");return{p:function(e,k){a.g(1,1)&&
(f.cookie=e+"="+k+";"+c(+new t+(b?6E10:6E4))+d)},n:function(b){if(a.g(1,1))return(f.cookie.match("(^|;)\\s*"+b+"=([^;]*)")||[])[2]||p},G:function(a){f.cookie=a+"=;"+c(0)+d}}}function F(a,b,c,d,e){b?a.call(q[b],c,d,e):z(q,function(b){a.call(b,c,d,e)})}function ia(a){var b=this;b.ja=0;var c=[];c[12]=b.b=a;b.s=function(a,d,k){4==a&&(ja(b,k,d),d=b.f);13==a&&(ja(b,"id",d),d=d||"-",X(b).da(d));c[a]=d};b.g=function(a,b){return a in c?c[a]:b};var d;b.fa=function(){d=r(qa(U,b),200)};b.F=function(){v(b.j);
v(d)}}function U(a,b,c){a&&a.call&&(c=a,a=p);b&&b.call&&(c=b,b=p);var d=this,e=va(d,a,b),g=wa(d),k=d.i===p&&!g.J;b=d.D=X(d);var h=xa(),u=Y(),f=d.g(5);b.S(1,k);v(d.j);d.m=0;d.h=0;Z(d);!d.g(9)&&e.U||e.T||K&&"preview"==K.loadPurpose||h.C&&h.B&&10>h.C&&10>h.B||(d.w=u.l,d.u=u.k,e={cs:h.P,cd:h.O,la:h.V,sw:h.C,sh:h.B,dp:h.R,pu:e.ga,pt:e.ea||"-",ri:g.J,ru:g.ba,re:b.ca,vi:b.r,pv:b.o,lv:b.W,vw:u.N,vh:u.L,dw:u.I,dh:u.H,st:u.l,sl:u.k,un:d.g(3),pp:b.$(),ec:f,aip:d.g(2)?1:p,tz:h.X},d.f&&(e.cp=M(d.f,1)),l&&(d.uid=
b.c,e.bc=1),G?(e.o_si=G,e.o_vi=$,e.o_ci=aa):d.K=1,d.Z=0,O(d,"pv",e,function(a){a!==p&&(d.i=a,v(d.j),d.j=r(s(P,d),5E3),c&&c())},5),d.i!==p?a!==p&&(d.i=p):(r(s(ya,d),500),x(m,"beforeunload",s(za,d))))}function V(a,b,c){D(a,"Event name is required");b&&b.call&&(c=b,b=p);if(b===""+b||b===+b)b={caption:b};b=sa(b||{});b.gs_evt_name=a;P(this,"event",b,c)}function P(a,b,c,d){if(a.i!==p){if(!c){var e=Y();c={vw:e.N,vh:e.L,dw:e.I,dh:e.H,st:e.l,sl:e.k,mst:a.w,msl:a.u}}c.i=a.i;c.e=b;c.et=Aa(a);l&&(c.bc=1);a.K&&
G&&(a.K=0,c.o_si=G,c.o_vi=$,c.o_ci=aa);O(a,"ping",c,function(){d&&d();v(a.j);a.j=r(s(P,a),[7E3,12E3][a.Z++]||17500+5E3*L.random())},5)}else r(function(){P(a,b,c,d)},5E3)}function ka(a){a.D?O(a,"prop",{cp:M(a.f,1)},s,5):r(function(){ka(a)},100)}function la(){var a=m.olark;a&&a("api.boot.onIdentityReady",function(a,c,d){G=a;$=c;aa=d})}function O(a,b,c,d,e){var g=r(function(){h&&h();ba=(ba+1)%ca[B];c.et&&(c.et=0);c.rt=1;--e&&O(a,b,c,d,e)},1E4),k=X(a);c.cb=Ba(function(a){d(a);h&&h();v(g)});c.a=a.b;c.au=
a.g(14);c.id=k.c;c.cid=k.M;c.tv=ea;var k=b+"?"+M(c),h;ma?ma.ha(k):h=Ca(k)}function Ca(a){var b=f[ga]("head")[0],c=f[fa]("script");c.src=(Da?"https":"http")+"://"+ca[ba]+a;b.appendChild(c);return function(){c&&b.removeChild(c);c=null}}function Ba(a){var b="_"+Ea++;N[b]=a;return b}function H(a){function b(){var a=d[w];a&&(d[w]=a[y](":_GS_:")[0])}var c;if(H[a])return H[a];var d=m.top;H[a]=c={Q:function(){b();d[w]=(d[w]||"")+":_GS_:"+[a,c.c,c.A]}};try{var e=d[w]||"";if(-1!=e[ha](":_GS_:")){var g=e[y](":_GS_:")[1][y](",");
g[0]==a&&(c.c=g[1]||"",c.A=g[2]||"")}b()}catch(k){d={}}return c}function va(a,b,c){var d=f[fa]("a");d.href=b||m.location.href;b=d.href;a.g(7,1)||(b=b[Q](/\?[^#]*/,""));a.g(8)||(b=b[Q](/#.*$/,""));return{ga:b,ea:c!==p?c:f.title,U:/^file:/.test(b)||/\/\/localhost[\/:]/.test(b+"/"),T:/fb_xd_(bust|fragment)/.test(b)}}function xa(){var a=0,b=0,c;A&&(a=A.width,b=A.height);c=(c=m.orientation)&&(c+360)%180;return{C:c?b:a,B:c?a:b,O:A&&A.colorDepth||"-",V:(K.language||K.browserLanguage||"-")[R](),P:f.characterSet||
f.charSet||"-",R:m.devicePixelRatio||1,X:(new t).getTimezoneOffset()}}function Y(){function a(a){return m["inner"+a]||c&&c[e="client"+a]||d&&d[e]}function b(a){return L.max(d[e="scroll"+a]||0,c[e]||0,d[e="offset"+a],c[e],d[e="client"+a],c[e])}var c=f.documentElement,d=f.body||c,e;return{N:a("Width"),L:a("Height"),I:b("Width"),H:b("Height"),k:m.pageXOffset||c&&c.scrollLeft||0,l:m.pageYOffset||c&&c.scrollTop||0}}function na(a){a.h&&(a.h=0,a.m=new t-a.t+(a.m||0))}function Z(a){v(a.Y);a.Y=r(s(na,a),15E3);
a.h||(a.h=1,a.t=new t)}function Aa(a){var b=a.m,c=new t;a.h&&(b+=c-a.t,a.t=c);a.m=0;return b}function Fa(a){Z(a);var b=Y();b.l>a.w&&(a.w=b.l);b.k>a.u&&(a.u=b.k)}function ya(a){var b=s(Z,a);x(f,"mousemove",b);x(f,"keydown",b);x(m,"scroll",s(Fa,a));x(f,"focus",b,"focusin");x(f,"blur",s(na,a),"focusout")}function wa(a){a=a.g(10,f.referrer);var b;!a||/^(chrome|about|file):/.test(a)||/^\[.*\]$/.test(a)?a="-":b=a[Q](/^.*?\/\//,"")[ha](location.host);return{J:+(0<=b&&8>=b),ba:a}}function za(a){if(a.i!==
p){var b=W(a);a.g(1,1)?b.p("gs_p_"+a.b,a.i):(b=H(a.b),b.A=a.i,b.Q())}}function X(a){function b(){k.p(e,h.c=[T,548*n.r+2019,379*n.o+4621,+new t].join(":"));a.s(11,T)}function c(){l&&"-"!==l?k.p(g,l):k.G(g)}function d(a){l=n.M=a;c()}var e="gs_u_"+a.b,g="gs_v_"+a.b,k=W(a,1),h=H(a.b),f=(k.n(e)||h.c||"")[y](":"),m=1,T=a.g(11,f[0])||(m=0,ra()),q=((f[1]||2019)-2019)/548,s=((f[2]||4621)-4621)/379,f=(f[3]||0)/1E3,l=a.g(13),r=k.n(g),n={c:T,M:l,r:q,o:s,W:~~f,ca:m,S:function(a,c){n.o+=+a;n.r+=+c;b()},da:d,ia:b,
$:function(){var b=k.n("gs_p_"+a.b)||h.A;k.G("gs_p_"+a.b);return a.i!==p?a.i:b}};r&&!l&&d(r);l&&c();return n}function ta(a,b,c,d){function e(a,b){b=b||(C(a)?a:{});C(a)||(b[w]=a);D(b[w],"No Name");h.push(b);return l}function g(a){for(var b=0;b<a[B];)e(a[b++]);return l}function f(){F(function(){var a=W(this,1),d="gs_t_"+this.b,e=a.n(d)||0;a.p(d,+new t);V.call(this,"_transaction",{d:JSON.stringify({id:b,pt:{ts:+e},i:h,d:c})})},a)}!c&&C(b)&&(c=b,b=c.id);D(b,"No ID");var h=[];d&&g(d);c&&c.track&&f();var l=
{id:b,addItem:e,addItems:g,track:f};return l}function ua(a,b){!b&&C(a)&&(b=a,a=b.id);D(a,"ID is required");this.s(13,a);b&&this.s(4,b)}var p,I,J=m._gs||(I=1,function(){oa.push(arguments)}),oa=J.q=J.q||[];if(!J.v){var q={},l=m.GoSquared;if(l){z(l,function(a,b){"acct"==b?(S(a,"_default",1),J(function(){function c(a){d[a.shift()].apply(d,a)}var d=l.DefaultTracker=q._default;if(b=l.q)for(;a=b.shift();)c(a);l.q={push:c};(b=l.load)&&b(d)})):"load"!=b&&"q"!=b&&J("set",b,a)});var n=ia.prototype;n.TrackView=
U;n.TrackEvent=V;n.Cancel=function(){this.F()};l.Tracker=S;l.Cancel=s(E,"cancel")}var G,$,aa,ca=["data.gosquared.com/","data2.gosquared.com/"],ba=0|L.random()*ca[B],Da=/^https:/.test(location.href),ma,N={},Ea=0;m._gs=E;for(E.v=ea;n=oa.shift();)E.apply({},n);if(I){I=f[ga]("script");for(var n=I[B],pa;n--;)(pa=I[n].getAttribute("data-gs"))&&E(pa)}la();x(m,"load",la)}})(window,document,navigator||{},screen,Math,Date,setTimeout,clearTimeout,encodeURIComponent,"6.3.1607","createElement","split","replace",
"length","toLowerCase","name","getElementsByTagName","indexOf");
